package com.br.senai.ads3.agenda_fatesg.pages;

import com.br.senai.ads3.agenda_fatesg.controllers.ContatoController;
import com.br.senai.ads3.agenda_fatesg.DependencyFactory;
import com.br.senai.ads3.agenda_fatesg.controllers.IContatoListaController;
import com.br.senai.ads3.agenda_fatesg.domains.Contato;
import com.br.senai.ads3.agenda_fatesg.dtos.ContatoCadastroDTO;
import com.br.senai.ads3.agenda_fatesg.enums.TipoTela;
import com.br.senai.ads3.agenda_fatesg.exceptions.BusinessException;
import com.br.senai.ads3.agenda_fatesg.exceptions.ValidationException;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import com.br.senai.ads3.agenda_fatesg.controllers.IContatoCadastroController;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author CLAYTON.MARQUES
 */
public class Form_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Form_Main
     *
     * @param tipoela
     */
    final private TipoTela tipoTela;
    private Contato contato;
    private final IContatoCadastroController contatoController;

    public Form_Cadastro(final TipoTela tipoTela, final Contato contato, final IContatoCadastroController controller) {
        this.tipoTela = tipoTela;
        if (contato == null) {
            this.contato = new Contato("", "", "");
        } else {
            this.contato = contato;
        }
        this.contatoController = controller;
        initComponents();
        
        // Ativação do arredondamento pelo FlatLaf
        this.pnDados.putClientProperty("FlatLaf.style", "arc: 30");
        this.edtNome.putClientProperty("FlatLaf.style", "arc: 10");
        this.edtTelefone.putClientProperty("FlatLaf.style", "arc: 10");
        this.edtEmail.putClientProperty("FlatLaf.style", "arc: 10");
        
        // Configura uma formatação profissional com máscara para o telefone: (DD) NNNNN-NNNN
        try {
            javax.swing.text.MaskFormatter maskTelefone = new javax.swing.text.MaskFormatter("(##) #####-####");
            maskTelefone.setPlaceholderCharacter('_');
            maskTelefone.install(this.edtTelefone);
        } catch (java.text.ParseException ex) {
            System.err.println("Erro ao aplicar máscara no telefone: " + ex.getMessage());
        }
        
        // Suavizando Botões e Labels com arc: 10
        this.btnGravar.putClientProperty("FlatLaf.style", "arc: 10");
        this.btnFechar.putClientProperty("FlatLaf.style", "arc: 10");
        
        this.setLocationRelativeTo(null);
        ajustaTela();
        carregaTela();
    }

    public Form_Cadastro(IContatoCadastroController controller) {
        this(TipoTela.INSERT, null, controller);
    }

    public Form_Cadastro() {
        this(DependencyFactory.getContatoCadastroController());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setLabelFor(edtNome);
        lblNome.setText("Nome completo:");
        lblNome.setName("lblNome"); // NOI18N

        edtNome.setName("edtNome"); // NOI18N
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });

        lblTelefone.setLabelFor(edtTelefone);
        lblTelefone.setText("Telefone:");
        lblTelefone.setName("lblTelefone"); // NOI18N

        edtTelefone.setName("edtelefone"); // NOI18N

        lblEmail.setLabelFor(edtEmail);
        lblEmail.setText("E-mail:");
        lblEmail.setName("lblNome"); // NOI18N

        edtEmail.setName("edtNome"); // NOI18N

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(27, 27, 27)
                        .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addGap(27, 27, 27)
                        .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(27, 27, 27)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agenda de Contatos");

        btnGravar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(pnDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnFechar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_edtNomeActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGravarActionPerformed
        String nomeNovo = edtNome.getText().trim();
        String email = edtEmail.getText().trim();
        String telefone = edtTelefone.getText().trim();
        boolean isEdit = this.tipoTela == TipoTela.EDIT;
        ContatoCadastroDTO dto = new ContatoCadastroDTO(nomeNovo, telefone, email);
        String originalName = this.contato != null ? this.contato.getNome() : "";

        // Executar I/O em background para não travar UI
        SwingWorker<Boolean, Void> worker = new SwingWorker<>() {
            @Override
            protected Boolean doInBackground() {
                try {
                    if (!isEdit) {
                        contatoController.criar(dto);
                    } else {
                        contatoController.alterar(originalName, dto);
                    }
                    return true;
                } catch (com.br.senai.ads3.agenda_fatesg.exceptions.CoreException ex) {
                    SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(Form_Cadastro.this, ex.getMessage(),
                            ex.getTitulo(), JOptionPane.WARNING_MESSAGE));
                } catch (Exception ex) {
                    SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(Form_Cadastro.this,
                            "Erro inesperado: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE));
                }
                return false;
            }

            @Override
            protected void done() {
                try {
                    boolean success = get();
                    if (success) {
                        // voltar para listagem
                        Form_Listagem list = new Form_Listagem(DependencyFactory.getContatoListaController());
                        list.setVisible(true);
                        dispose();
                    }
                } catch (Exception e) {
                    // ignorar interrupções
                }
            }
        };
        worker.execute();
    }// GEN-LAST:event_btnGravarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        new Form_Listagem().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Usa o ThemeManager para plugar Fontes Nativas Globais ANTES das GUIs subirem
        com.br.senai.ads3.agenda_fatesg.util.ThemeManager.setupTheme();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Form_Cadastro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JFormattedTextField edtTelefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnDados;
    // End of variables declaration//GEN-END:variables

    private void ajustaTela() {
        boolean habilita = true;
        if (this.tipoTela == TipoTela.VIEW) {
            habilita = false;
        }

        this.btnGravar.setVisible(habilita);
        this.edtTelefone.setEnabled(habilita);
        this.edtEmail.setEnabled(habilita);
        this.edtNome.setEnabled(habilita);

        this.revalidate();
        this.repaint();
    }

    private void carregaTela() {
        if (this.contato == null) {
            this.contato = new Contato("", "", "");
        }
        this.edtNome.setText(this.contato.getNome());
        this.edtTelefone.setText(this.contato.getTelefone());
        this.edtEmail.setText(this.contato.getEmail());
    }
}
