package com.br.senai.ads3.agenda_fatesg.pages;

import com.br.senai.ads3.agenda_fatesg.DependencyFactory;
import com.br.senai.ads3.agenda_fatesg.domains.Contato;
import com.br.senai.ads3.agenda_fatesg.enums.TipoTela;
import java.awt.EventQueue;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.SwingUtilities;
import com.br.senai.ads3.agenda_fatesg.controllers.IContatoListaController;

/**
 *
 * @author CLAYTON.MARQUES
 */
public class Form_Listagem extends BasePage {

    private static final long serialVersionUID = 1L;
    private final IContatoListaController contatoController;

    /**
     * Creates new form Form_Listagem
     * @param controller
     */
    public Form_Listagem(IContatoListaController controller) {
        super("Agenda de Contatos - Listagem");
        this.contatoController = controller;
        initComponents();
        
        // Ativação do arredondamento pelo FlatLaf via BasePage
        applyArc(this.jPanel1, 30);
        applyArc(this.edtFiltroNome, 10);
        
        // Suavizando bordas de outros componentes
        applyArc(this.btnAdicionar, 10);
        applyArc(this.btnExcluir, 10);
        applyArc(this.btnFechar, 10);
        
        // Arrendondando a Tabela de listagem via BasePage
        applyArc(this.jScrollPane1, 10);
        
        carregarDadosAsync();
    }

    public Form_Listagem() {
        this(DependencyFactory.getContatoListaController());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        edtFiltroNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnWhatsApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contatos da agenda");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel2.setText("Filtro");

        jLabel3.setLabelFor(edtFiltroNome);
        jLabel3.setText("Buscar por nome:");

        btnAdicionar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnAdicionar.setText("Novo contato");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        edtFiltroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtFiltroNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAdicionar))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAdicionar)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        grid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "E-mail", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grid.setShowGrid(true);
        grid.getTableHeader().setReorderingAllowed(false);
        grid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grid);

        btnFechar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnWhatsApp.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnWhatsApp.setText("WhatsApp");
        btnWhatsApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhatsAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnWhatsApp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(301, 301, 301)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnExcluir)
                    .addComponent(btnWhatsApp))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridMouseClicked
        if (evt.getClickCount() == 2) { // duplo clique
            int linhaVisual = grid.getSelectedRow();
            int linha = grid.convertRowIndexToModel(linhaVisual);

            if (linha != -1) {
                String nome = (String) grid.getModel().getValueAt(linha, 0);
                if (nome == null) nome = "";
                String email = (String) grid.getModel().getValueAt(linha, 1);
                if (email == null) email = "";
                String telefone = (String) grid.getModel().getValueAt(linha, 2);
                if (telefone == null) telefone = "";

                Form_Cadastro cadastro = new Form_Cadastro(TipoTela.EDIT, new Contato(nome, email, telefone), DependencyFactory.getContatoCadastroController());
                cadastro.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_gridMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Form_Cadastro cadastro = new Form_Cadastro(DependencyFactory.getContatoCadastroController());
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void edtFiltroNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtFiltroNomeKeyReleased
        DefaultTableModel modelo = (DefaultTableModel) grid.getModel();
        TableRowSorter<DefaultTableModel> filtro = new TableRowSorter<>(modelo);
        grid.setRowSorter(filtro);
        filtro.setRowFilter(RowFilter.regexFilter("(?i)" + edtFiltroNome.getText(), 0));
    }//GEN-LAST:event_edtFiltroNomeKeyReleased

    private void btnWhatsAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatsAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWhatsAppActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int linhaVisual = grid.getSelectedRow();
        if (linhaVisual == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um contato para excluir.");
            return;
        }
        int linha = grid.convertRowIndexToModel(linhaVisual);
        String nome = (String) grid.getModel().getValueAt(linha, 0);
        if (nome == null || nome.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nome inválido.");
            return;
        }
        int resp = JOptionPane.showConfirmDialog(this, "Confirma exclusão lógica do contato '" + nome + "'?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resp != JOptionPane.YES_OPTION) {
            return;
        }

        // Executar I/O em background com Virtual Threads (Padrão 2026 / Java 21)
        Thread.ofVirtual().start(() -> {
            try {
                boolean ok = contatoController.inativarPorNome(nome);
                
                SwingUtilities.invokeLater(() -> {
                    if (ok) {
                        JOptionPane.showMessageDialog(Form_Listagem.this, "Contato marcado como inativo.");
                        carregarDadosAsync(); // recarrega tabela
                    } else {
                        JOptionPane.showMessageDialog(Form_Listagem.this, "Contato não encontrado ou já inativo.");
                    }
                });
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(Form_Listagem.this, "Erro ao excluir: " + ex.getMessage()));
            }
        });
    }// GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnWhatsApp;
    private javax.swing.JTextField edtFiltroNome;
    private javax.swing.JTable grid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void carregarDadosAsync() {
        // Executar carregamento em background com Virtual Threads
        Thread.ofVirtual().start(() -> {
            try {
                List<Contato> list = contatoController.listarTodosAtivos();
                SwingUtilities.invokeLater(() -> populateTable(list));
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(Form_Listagem.this, "Erro ao carregar dados: " + ex.getMessage()));
            }
        });
    }

    private void populateTable(List<Contato> contatos) {
        if (contatos == null) return;
        DefaultTableModel modelo = (DefaultTableModel) grid.getModel();
        modelo.setNumRows(0);
        for (Contato c : contatos) {
            modelo.addRow(new Object[]{c.getNome(), c.getEmail(), c.getTelefone()});
        }
    }
}
